<a href="https://colab.research.google.com/github/pouyyan/ML_Course_2024/blob/main/HW1/HW1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 6

In [ ]:
import numpy as np
import timeit
def operation1(m, n, A, k):
    p_1 = np.zeros(m)
    for i in range(n):
        p_1 += A[:, i] * k[i]
    return p_1
def operation2(A,k):
  p_2 = np.matmul(A,k)
  #p_2 = A@k
  return p_2
m,n = 20, 10
A = np.random.rand(m,n)
k = np.random.rand(n)
result1 = operation1(m, n, A, k)
print("Result1:", result1)
result2 = operation2(A, k)
print("Result2:", result2)
compare = np.allclose(result1,result2)
# Time operation1
time1 = timeit.timeit(lambda: operation1(m, n, A, k), number=10)
# Time operation2
time2 = timeit.timeit(lambda: operation2(A, k), number=10)
print(f"Execution time for operation1: {time1:.6f} seconds")
print(f"Execution time for operation2: {time2:.6f} seconds")
print('Are the results identical? ',compare)

Result1: [2.58998351 2.31699747 3.42452658 2.23451374 2.44280889 2.85213946
 2.31532298 3.77134326 2.56279533 2.22130763 2.99949743 3.21036688
 1.64153526 2.07533525 2.95535827 2.33971217 2.88579303 3.13507516
 3.74290765 2.67472741]
Result2: [2.58998351 2.31699747 3.42452658 2.23451374 2.44280889 2.85213946
 2.31532298 3.77134326 2.56279533 2.22130763 2.99949743 3.21036688
 1.64153526 2.07533525 2.95535827 2.33971217 2.88579303 3.13507516
 3.74290765 2.67472741]
Execution time for operation1: 0.000446 seconds
Execution time for operation2: 0.000046 seconds
Are the results identical?  True


# Question 5

In [77]:
import numpy as np
n = 5
A = np.random.rand(n, n)
A = np.triu(A)
determinant = np.linalg.det(A)
print('Triangular matrix: ',A)
if determinant != 0:
    print("Matrix is nonsingular.")
else:
    print("Matrix is singular.")

Triangular matrix:  [[0.50938871 0.00811376 0.99179899 0.0124497  0.81030299]
 [0.         0.45436771 0.36206902 0.99728733 0.87643057]
 [0.         0.         0.37228715 0.30366078 0.85264981]
 [0.         0.         0.         0.73511604 0.4011853 ]
 [0.         0.         0.         0.         0.15711576]]
Matrix is nonsingular.
